{
 "title": "DCGM-GPU Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "DCGM_FI_DEV_GPU_TEMP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_TEMP", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DCGM_FI_DEV_FB_USED",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "DCGM_FI_DEV_FB_USED", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DCGM_FI_DEV_POWER_USAGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "DCGM_FI_DEV_POWER_USAGE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DCGM_FI_DEV_GPU_UTIL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_UTIL", "legendFormat": "__auto" }
   ]
  }
 ]
}