apiVersion: apps/v1
kind: Deployment
metadata:
  name: ort-server
  namespace: aimodel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ort-server
  template:
    metadata:
      labels:
        app: ort-server
    spec:
      volumes:
        - name: model
          hostPath:
            path: /home/faraz/aimodel/AIModel/model   # host directory on your VM
            type: Directory
      containers:
        - name: ort
          image: mcr.microsoft.com/onnxruntime/server
          imagePullPolicy: IfNotPresent
          args:
            - "--model_path=/models/resnet50.onnx"    # ✅ fixed path
            - "--http_port=8000"
            - "--grpc_port=8001"
            - "--log_level=info"
          ports:
            - name: http
              containerPort: 8000
            - name: grpc
              containerPort: 8001
          volumeMounts:
            - name: model
              mountPath: /models
          readinessProbe:
            tcpSocket:
              port: 8001
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            tcpSocket:
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
