apiVersion: v1
kind: Service
metadata:
  name: ort-server
  namespace: aimodel
spec:
  type: NodePort
  selector:
    app: ort-server
  ports:
    - name: http
      port: 8000
      targetPort: http
      nodePort: 30080
    - name: grpc
      port: 8001
      targetPort: grpc
      nodePort: 30081
