apiVersion: v1
kind: Service
metadata:
  name: resnet50-service
  namespace: aimodel
  labels: { app: resnet50 }
spec:
  type: ClusterIP
  selector:
    app: resnet50
  ports:
    - name: grpc
      port: 8500
      targetPort: 8500
    - name: rest
      port: 8501
      targetPort: 8501
