apiVersion: apps/v1
kind: Deployment
metadata:
  name: resnet50-tfserving
  namespace: aimodel
  labels: { app: resnet50 }
spec:
  replicas: 1
  selector:
    matchLabels: { app: resnet50 }
  template:
    metadata:
      labels: { app: resnet50 }
    spec:
      # single-node control-plane cluster needs these tolerations
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          effect: "NoSchedule"
      containers:
        - name: tfserving
          image: tensorflow/serving:2.14.0
          imagePullPolicy: IfNotPresent
          args:
            - --port=8500
            - --rest_api_port=8501
            - --model_name=resnet50
            - --model_base_path=/models/resnet50
          ports:
            - containerPort: 8500
            - containerPort: 8501
          volumeMounts:
            - name: model-volume
              mountPath: /models/resnet50
              readOnly: true
          # optional quick probe; service answers once model is loaded
          readinessProbe:
            httpGet:
              path: /v1/models/resnet50
              port: 8501
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 12
      volumes:
        - name: model-volume
          hostPath:
            path: /home/emulate/models/resnet50
            type: Directory
