# resnet50-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resnet50-tfserving
  namespace: aimodel
  labels: { app: resnet50 }
spec:
  replicas: 1
  strategy:
    type: Recreate                  # ensures only 1 pod during an update
  selector:
    matchLabels: { app: resnet50 }
  template:
    metadata:
      labels: { app: resnet50 }
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          effect: "NoSchedule"
      containers:
        - name: tfserving
          image: docker.io/faraz2079/resnet50-serving:2   # bump tag
          imagePullPolicy: IfNotPresent
          args:
            - --port=8500
            - --rest_api_port=8501
            - --model_name=resnet50
            - --model_base_path=/models/resnet50
            - --monitoring_config_file=/config/monitoring_config.pbtxt
          ports:
            - name: grpc
              containerPort: 8500
            - name: rest
              containerPort: 8501
          readinessProbe:
            httpGet:
              path: /v1/models/resnet50
              port: 8501
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 12
          volumeMounts:
            - name: monitoring-config
              mountPath: /config
              readOnly: true
      volumes:
        - name: monitoring-config
          configMap:
            name: resnet50-monitoring
            items:
              - key: monitoring_config.pbtxt
                path: monitoring_config.pbtxt
