# resnet50-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resnet50-tfserving
  namespace: aimodel
  labels: { app: resnet50 }
spec:
  replicas: 1
  strategy:
    type: Recreate                # <<< only 1 pod during updates (downtime while restarting)
  selector:
    matchLabels: { app: resnet50 }
  template:
    metadata:
      labels: { app: resnet50 }
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          effect: "NoSchedule"
      containers:
        - name: tfserving
          image: tensorflow/serving:2.14.0
          imagePullPolicy: IfNotPresent
          args:
            - --port=8500
            - --rest_api_port=8501
            - --model_name=resnet50
            - --model_base_path=/models/resnet50
            - --monitoring_config_file=/config/monitoring_config.pbtxt   # <<< pbtxt, not JSON
          ports:
            - containerPort: 8500
            - containerPort: 8501
          volumeMounts:
            - name: model-volume
              mountPath: /models/resnet50
              readOnly: true
            - name: monitoring-config
              mountPath: /config
              readOnly: true
          readinessProbe:
            httpGet:
              path: /v1/models/resnet50
              port: 8501
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 12
      volumes:
        - name: model-volume
          hostPath:
            path: /home/emulate/models/resnet50
            type: Directory
        - name: monitoring-config
          configMap:
            name: resnet50-monitoring
            items:
              - key: monitoring_config.pbtxt
                path: monitoring_config.pbtxt
